      - name: Build
        run: |
          export ZEPHYR_SDK_INSTALL_DIR=$HOME/zephyr-sdk/zephyr-sdk-0.16.8
          cd zmk/app
          west build -b xiao_ble -- -DZMK_CONFIG=${{ github.workspace }}/config
